### ISSUE TITLE
Add HTTP methods to frapi

### ISSUE THREAD

**Issue by Max13** [frapi/frapi#106]
Hi !
Is there a way to add some other HTTP methods to frapi ?
Like for example, PATCH, OPTIONS, TRACE...?

If there is, can you please tell me how to do that ?

Thanks.

**Comment by davidcoallier** [comment]
If you define your method like:

``` php
public function executePath(...) {..}
```

I think it should pick it up. :-)

**Comment by Max13** [comment]
I'll test it thanks !

**Comment by Max13** [comment]
Works great, even with custom method name...
Good work ;)

**Comment by Max13** [comment]
Hey !
It's working... But it doesn't call the "executeAction".
Known bug?
