### ISSUE TITLE
Modify "new action" files

### ISSUE THREAD

**Issue by Max13** [frapi/frapi#107]
Hi,

I'm using frapi, and for all my apis, I'm adding manually my custom functions and variables (like an init, which does the same thing on all actions, all files).

Is There a way to modify custom action default page ? Un order to add my custom function for every new actions?

Thanks

**Comment by dshafik** [comment]
You create a base action class that extends `Frapi_Action` then modify each action to extend this base class instead.

**Comment by Max13** [comment]
Actually, I'm using DoxyGen to generate my docs.
And for DoxyGen, the @link and @author don't have the right syntaxe.

I really want to change the generated file. I will extends Frapi_action as well, but need to modify the generated file.

Thanks.
