### ISSUE TITLE
returning Frapi_Error from an action errors when output is JSON

### ISSUE THREAD

**Issue by clayhinson** [frapi/frapi#109]
The JSON output class expects its data to be an array, and cannot handle a Frapi_Error object. 

throwing the Frapi_Error causes it to be handled properly, but the default code template uses return if validation errors occur. 

The generated action should throw Frapi_Error by default and the documentation may need to be updated to reflect this.

**Comment by dshafik** [comment]
From the IRC meeting: We're going to update the template to correctly throw the error instead of returning it.

**Comment by clayhinson** [comment]
code reference: https://github.com/frapi/frapi/blob/master/src/frapi/admin/application/modules/default/models/Action.php#L527
