### ISSUE TITLE
RouterTest::testStaticOverDynamic causes "Only variables should be passed by reference" error

### ISSUE THREAD

**Issue by jeremykendall** [frapi/frapi#11]
The test in question makes liberal use of php's end() function - ex. 

```
end($router->match('route-name'))
```

From the docs (http://php.net/end):

> "The . . . array is passed by reference because it is modified by the function. This means you must pass it a real variable and not a function returning an array because only actual variables may be passed by reference."

Working on this now.

**Comment by jeremykendall** [comment]
Resolved in commit: http://github.com/jeremykendall/frapi/commit/d31d6d41a087c944e705a1364ef5a79856e02003

Diff is here: http://github.com/jeremykendall/frapi/commit/d31d6d41a087c944e705a1364ef5a79856e02003#diff-10

**Comment by davidcoallier** [comment]
Applied.
