### ISSUE TITLE
Previously closed: Modify "new action" files

### ISSUE THREAD

**Issue by Max13** [frapi/frapi#110]
Hi,

My previous "issue" has been closed and I "don't have permission to reopen it".
So, I explain my "issue".

I want to create a class, which extends "Frapi_Action". And my final generated files will extends my class.
I'm using DoxyGen, and I also want to modify the @link and @author which have a wrong syntax.

So, I want to modify the generated class (when creating a new action) to make them extands the right class, and to rewrite the comments.

Can you tell me how to do that please ?
Thanks.

**Comment by dshafik** [comment]
@Max13 Just edit the Action files by hand; FRAPI will not overwrite your changes.

**Comment by Max13** [comment]
I'm currently doing it, but it's heavy to do that for all my frapi projects files and new files.
That's why i'm asking.

Isn't it possible ?

**Comment by davidcoallier** [comment]
It's possible but will not be forward compatible when you update/upgrade FRAPI. You'll have to modify the file https://github.com/frapi/frapi/blob/master/src/frapi/admin/application/modules/default/models/Action.php#L442 and change the line linked to have the name of your class. Make sure that your base class extends Frapi_Action otherwise you'll end up with weird behavioural issues.

Disclaimer: **I do not recommend doing it, but it's possible :-)**

**Comment by Max13** [comment]
Ok okay...
I won't do it.

But thank you anyway.
PS: Which doc generator can generate api doc with frapi ?

**Comment by davidcoallier** [comment]
From the administration panel you access the URL:
- /docs/generate/format/mdown
- /docs/generate/format/html

It'll generate the docs from your defined actions :)

**Comment by davidcoallier** [comment]
Keep in mind that the goal of frapi is to generate end-user documentation and not API documentation. Should you wish to generate API docs, I'd recommend using Doxygen as you do or phpdox or phpDocumentor and run it on the `custom/` folder.

**Comment by Max13** [comment]
End-user doc, in this case, isn't it the same as API doc?
(I'm asking because I don't find the folder /docs/generate, I'm checking the repo.)

Edit: Sorry, I didn't read "from the admin panel -_-"
The cons of using doxygen, is that it's not very clear. "executePost()" is shown instead of "POST", I think it's not suitable for API Doc.
Yours seems to be better ;)
