### ISSUE TITLE
Function $this->getParam()

### ISSUE THREAD

**Issue by dinhienhy** [frapi/frapi#113]
Hi all,

I have tried a function: $this->getParam('name', self::TYPE_STRING) then result has been empty string.
But I have used a  function $_GET['name'] then I have received correct value.
Please give me an advice!

Thanks

**Comment by dshafik** [comment]
Do you have a :name param in your route? Have you done a `var_dump($this->getParams())`?

**Comment by dinhienhy** [comment]
I have a :name param in my route. 
When I try var_dump($this->getParams()), I see all params which I have added in the request.

**Comment by davidcoallier** [comment]
`getParams(...)` will return all GETs, POST, from your request as well as your route.

**Comment by dinhienhy** [comment]
I know that. But I don't understand why $this->getParam('name', self::TYPE_STRING) can't give me a right result.

**Comment by dshafik** [comment]
I believe the issue here is that `:name` in the route will override the `name` var in the GET query string; do you have a value for `:name` being passed in? Can you provide the following:
1. The relevant section of your `actions.xml`
2. The URL being used to access it (we don't need the domain, just the path and GET string)
3. The `var_dump($this->getParams())` output

**Comment by dinhienhy** [comment]
Please see bellow information:
1. The relevant section of my actions.xml

  <action>
   <name>Users</name>
   <enabled>1</enabled>
   <public>1</public>
   <description>This action handles GET, POST, HEAD of a user</description>
   <route>/users/:user_id</route>
   <parameters></parameters>
   <hash>6eddacc22a320fc7afc0008fadca2b0e707cc93b</hash>
  </action>
1. URL:
   /users/19.json
2. The var_dump($this->getParams()) output:
   array(2) {
   ["name"]=>
   string(5) "steve"
   ["user_id"]=>
   string(2) "19"
   }

**Comment by davidcoallier** [comment]
This is strange. Did you `POST` the parameter "name=steve" when doing the request? Where is `steve` coming from?

**Comment by dinhienhy** [comment]
I have added the parameter "name=steve" when doing the request. You don't care about it. I just wanted to test this request.

**Comment by davidcoallier** [comment]
I believe I've found the issue. Which version are you using? Downloaded or Git checkout?

**Comment by dinhienhy** [comment]
I have used version frapi-frapi-55c7f1f. I have downloaded it.

**Comment by davidcoallier** [comment]
This should fix it.

**Comment by dinhienhy** [comment]
Thanks  davidcoallier.
It's so cool.
