### ISSUE TITLE
APC Cache cleared at end of scripts

### ISSUE THREAD

**Issue by Max13** [frapi/frapi#114]
Hi,
I'm trying to set and verify apc_store with ttl at 30sec.
When I reload the script, the cache seems to be empty.

Is it a normal behaviour ?

Thanks for your help.

**Comment by dshafik** [comment]
I have added this to the Runner milestone and will look into it when I get a chance. If this is indeed the case, it should definitely be fixed.

**Comment by Max13** [comment]
Thanks

**Comment by dragonmantank** [comment]
@Max13 What way are you running PHP? If you are running regular CGI your cache would clear after every request, but FastCGI or mod_php should live until TTL ends or the process dies due to it reaching the maximum number of requests.

**Comment by Max13** [comment]
@dragonmantank We're running PHP as CGI. Are you saying that as CGI, PHP ignores the [$ttl](http://fr.php.net/manual/en/function.apc-add.php) value ?

**Comment by dragonmantank** [comment]
The memory pool is destroyed when the PHP process ends. With regular CGI this would be after every request, but with FastCGI or mod_php the pool will last for much longer. I guess if your CGI would run longer than the TTL it would persist, but generally your script will end before your TTL is reached.

**Comment by dshafik** [comment]
The best solution is to use the memcache adapter for caching; simply change the constant in `custom/AllFiles.php` to:

`define('FRAPI_CACHE_ADAPTER', 'memcache');`

This will use a memcache install on port `localhost:11211`.

The APC cache adapter is not compatible with CGI.
