### ISSUE TITLE
old download

### ISSUE THREAD

**Issue by DanielRuf** [frapi/frapi#117]
it is from 2010?

**Comment by davidcoallier** [comment]
Sorry? Could you elaborate a little bit on what you mean please? :)

**Comment by DanielRuf** [comment]
The download https://github.com/frapi/frapi/downloads is very old
Is there a new one or should we just grab the full repo?

**Comment by davidcoallier** [comment]
Go to the same page, and don't click on : 
latest.tar.gz — Latest FRAPI From 25/5/2010

Use the one above, the button that says: **Download as tar.gz**

**Comment by DanielRuf** [comment]
well so you could delete it?

or zip ;-)

**Comment by davidcoallier** [comment]
Done
