### ISSUE TITLE
Lupin_Security::escape() throws E_STRICT

### ISSUE THREAD

**Issue by jeremykendall** [frapi/frapi#12]
Error

> Strict standards: call_user_func() expects parameter 1 to be a valid callback, non-static method Lupin_Security::escape() should not be called statically

**Comment by jeremykendall** [comment]
Resolved in http://github.com/jeremykendall/frapi/commit/9d3be4f6305b7b2c4a8c3ec744abf3c6b27af8c5

**Comment by davidcoallier** [comment]
Fixed http://github.com/frapi/frapi/commit/f1e9d59051852abbdd5b29f19bb5cae70e30541d
