### ISSUE TITLE
Loading an endpoint in a browser causes FRAPI to return HTML output, even when disabled

### ISSUE THREAD

**Issue by funkatron** [frapi/frapi#120]
We have HTML output disabled in outputs.xml, but when we load an endpoint in a browser, it attempts to output via HTML. This causes an error to be displayed about missing template files (which is also a disclosure concern).

I'd prefer it to throw a 412 error if possible.

**Comment by dshafik** [comment]
This should be completely resolved with #145, please confirm and reopen the issue (or create a new one) if you are still having problems.

**Comment by funkatron** [comment]
thanks!
