### ISSUE TITLE
Problem installing FRAPI

### ISSUE THREAD

**Issue by Romain77** [frapi/frapi#122]
Hi there, i have follow the "how to" install FRAPI on your manual.

But I have a problem when i try to reach http://admin.frapi (and api.frapi) i have : 

"Fatal error: Call to undefined function apc_fetch() in /var/www/frapi/src/frapi/library/Frapi/Cache/Adapter/Apc.php on line 35"

For informations, i have try to install it on a ubuntu server 10.04. If you need more informations/parameters of my Apache server, feel free to ask !

I am a little bit lost ! I am not an expert and i need a webservice to allow my iOS and Android Apps to make request on a mySQL DB :(

Thanks for help

**Comment by davidcoallier** [comment]
Hi there Romain, 

You'll have to install `apc` using `pecl` (The command). Here's how to install PHP Extensions: http://php.net/manual/en/install.pecl.php

Hope this helps

**Comment by Romain77** [comment]
Ok ... thanks for your very quick answer

I will post here if i still have troubles (hope no) :p

**Comment by Romain77** [comment]
hi again :(

So i have correctly install apc via pecl install apc. i have add "extension=apc.so" to my php.ini in /etc/php5/apache2

I have restart my apache server (don't know really why ... but i ve did it :p)

but i have EXACTLY the same error when i try to reach http://admin.frapi

:( An idea where it can continue to block ?

**Comment by Romain77** [comment]
OK ... i have found

I have make a apt-get install php-apc and it finally works :) :)

Thanks and Have a nice day

**Comment by davidcoallier** [comment]
Pleasure :) Feel free to ask any question at any given time. I'm happy it is now working for you :) Just to make sure, you should check out http://frapi.github.com for maintained documentation :)

**Comment by Romain77** [comment]
:) 

I am already work with this documentation :) But as I told you, i am an totally beginner :) And i have now to understand how i can use FRAPI to assure the connection between my mobiles apps and the mySQL DB on my ubuntu server :)

So i will maybe (surely) ask you more questions about that .. :) 

And the first one just like that :) Do i have to make admin.frapi and api.frapi reachable over the web to be used as webservices ? of course yes ? (I ask the question just to be sure and to be advice on how to do it for frapi correctly) :)

**Comment by davidcoallier** [comment]
Only make api.frapi accessible over the web using your own domain name. We dont' recommend making the administration panel available. The admin should be for development only.

**Comment by Romain77** [comment]
Ok great ... it was to be sure enough and not doing mistakes :p

I will do that and check for all this things frapi offer :p

**Comment by mirlo06** [comment]
hi , 
during the installation of frapi on windows  I get an error, "Internal Server Error 500"  what should I do? help me thanks.

**Comment by DanielRuf** [comment]
Will there be also a version which doesnt need apc? Do webhosting providers have apc installed and activated?

**Comment by kislah** [comment]
thanks! the php install was the key
