### ISSUE TITLE
Frapi installed but now ??? 

### ISSUE THREAD

**Issue by Romain77** [frapi/frapi#125]
Hi there, 

Sorry for the level of my question but i have install frapi, parameter the api side to be reachable over the web but now i have dont with that, i don't really understant how and what i have to do to continue with my project. 

Acutally i am looking for a webservice to "link" a mySQL DB and an iOS application.

So actually the question is ? how to setup the connection between my DB and Frapi for the "frist step" and after that how test it to be sure it works. 

I have tried to follow up your documentation but my skills are too low to properly understand what you mean. 

Thanks for help ... i really want to understand how frapi works because it is a first project but the thing i am sure, is i will need to configure severals webservices in a short future ... that s why i need to learn how to use it ... but for now ... i am not in :(

**Comment by Romain77** [comment]
No Body could help to understand how to continue ... the second step and where to look for ?

**Comment by davidcoallier** [comment]
You need to create an **action** which will use a **model** to connect to your mysql database with your business logic.

**Comment by Romain77** [comment]
Ok .. :)

I saw that in your tutorial ... I have follow it and create a "user" DB but after that, i don't really understand the coding party ... in your example, you do not explain how to write someting in the user DB or read something from it. That's the probleme i have actually !

**Comment by davidcoallier** [comment]
You will need a bit of knowledge of how to write PHP. Basically a model could look like:

``` php
<?php

class My_Model {
    public $db;
    public function __construct() 
    {
        $this->db = Frapi_Database::getInstance();
    }

    public function getLogEntries($limit = 100)
    {
        $sql = "SELECT * FROM logentries LIMIT $limit";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();

        return $stmt->fetchAll();
    }
}

```

and so forth. I would suggest reading tutorials on how to use **php** and **mysql**. This is a half-decent book: http://shop.oreilly.com/product/9780596514013.do

**Comment by Romain77** [comment]
Hmm Ok thanks for your answer ! Effectively, i am not so much familiar with Php ... 

But just for example and in order to show me how it works ... 

Considering that i followed the tutorial so : 

I have create actions as aked on it, i have create a "user database" with a "users table" and i have setup my database "connection" from the admin panel (Configuration -> database)

And always as an example, imagine i want to code an action "executeGet()" to write something on my database ! How would you write it from the generated php page generated by Frapi after the action is created.

I just want to understant how it works ! Of course i will need to read about php and mysql but for now i just want to understand what i need to know ...

The generated code : 

<?php

/**
- Action Users 
- 
- Array
- 
- @link http://getfrapi.com
- @author Frapi frapi@getfrapi.com
- @link /users/:user_id
  */
  class Action_Users extends Frapi_Action implements Frapi_Action_Interface
  {
  
  /**
  - Required parameters
  - 
  - @var An array of required parameters.
    */
    protected $requiredParams = array();
  
  /**
  - The data container to use in toArray()
  - 
  - @var A container of data to fill and return in toArray()
    */
    private $data = array();
  
  /**
  - To Array
  - 
  - This method returns the value found in the database 
  - into an associative array.
  - 
  - @return array
    */
    public function toArray()
    {
    return $this->data;
    }
  
  /**
  - Default Call Method
  - 
  - This method is called when no specific request handler has been found
  - 
  - @return array
    */
    public function executeAction()
    {
    return $this->toArray();
    }
  
  /**
  - Get Request Handler
  - 
  - This method is called when a request is a GET
  - 
  - @return array
    */
    public function executeGet()
    {
    return $this->toArray();
    }
  
  /**
  - Post Request Handler
  - 
  - This method is called when a request is a POST
  - 
  - @return array
    */
    public function executePost()
    {
    return $this->toArray();
    }
  
  /**
  - Put Request Handler
  - 
  - This method is called when a request is a PUT
  - 
  - @return array
    */
    public function executePut()
    {
    return $this->toArray();
    }
  
  /**
  - Delete Request Handler
  - 
  - This method is called when a request is a DELETE
  - 
  - @return array
    */
    public function executeDelete()
    {
    return $this->toArray();
    }
  
  /**
  - Head Request Handler
  - 
  - This method is called when a request is a HEAD
  - 
  - @return array
    */
    public function executeHead()
    {
    return $this->toArray();
    }

}

Again thanks a lot for help

**Comment by Romain77** [comment]
MayBe juste a precision instead of write me an action as example ... 

We can define some parameters for a Database in frapi admin panel. But How those parameter could be call from the php code ? 

But i still interested if someone accept to show me an example as i told about in my previous comment :p

Again thanks for help

**Comment by davidcoallier** [comment]
1. Go to the frapi admin
2. Go to configuration
3. Click on the left handside menu (Database)
4. Configure your mysql database
5. In your models, use `$db = Frapi_Database::getInstance();`

**Comment by Romain77** [comment]
Great Thanks

**Comment by dshafik** [comment]
I'm going to close this issue as there is no bug. For more questions of this sort, I recommend the [frapi-general mailing list/google group](https://groups.google.com/forum/?fromgroups#!forum/frapi-general).
