### ISSUE TITLE
Better support for FRAPI as a submodule

### ISSUE THREAD

**Issue by dshafik** [frapi/frapi#127]
Currently, the way FRAPI handles the `custom` directory makes it difficult to include FRAPI as a submodule, making it more difficult than necessary to have FRAPI as a vendor upstream for building projects upon.

We need to make the `custom` directory configurable using an environment variable; this enables you to easily locate the `custom` directory outside of the remote.

**Comment by clayhinson** [comment]
Agreed. every FRAPI install I set up has to be modified in order to be able to store custom/ as a separate repo.

**Comment by dshafik** [comment]
This is fixed in #132
