### ISSUE TITLE
ace editor prevents Action editing

### ISSUE THREAD

**Issue by the3rdbit** [frapi/frapi#130]
When I try to edit an action, the description < textarea > gets hidden and (style="display: none;") and a white square < div > appears.

Apparently there should be something in the ace folder but it's empty!
https://github.com/frapi/frapi/tree/master/src/frapi/admin/public/js

When I include the ace library, I get an empty editor (even when there should be a description) and the following errors appear:
`GET http://admin.frapi/js/ace/build/src/theme-textmate.js 404 (Not Found)
ace.js:1Missing module: ../lib/oop
ace.js:1Missing module: ./text
mode-markdown.js:1Uncaught TypeError: Cannot read property 'Mode' of null`

My workaround for the moment: remove "display: none;" in the < textarea > each time I want to edit an action...
<a href="http://www.bild.me/bild.php?file=7817445FRAPI_Admin_Interface_-_Iron_2012-04-20_14-45-22.png" target="_blank"><img src="http://s1.bild.me/bilder/060112/thumb_7817445FRAPI_Admin_Interface_-_Iron_2012-04-20_14-45-22.png" border="1"></a>

Same problem with git installation and http download.
Tested Browsers: Chrome 17, FF 11

Cheers

P.S. I've tried to get help in your IRC channel but I've only got an answer from someone who has the same problem as me

**Comment by clayhinson** [comment]
The ace editor is a git submodule. To get it, clone the FRAPI git repository, `cd` into it, and run `git submodule update --init`. This will set up the ace editor in your FRAPI admin. We have an open issue to make it clearer that this needs to be done.

**Comment by the3rdbit** [comment]
Thanks, this ace version works great!
Finally got a machine with Internet access to Git from where I took the files. There should be a way to download this version of the editor from HTTP...

**Comment by brianherbert** [comment]
I'm seeing this same issue except I'm just running the base install of FRAPI, following the instructions in the docs (http://frapi.github.com/developing/creating-actions.html).

<img src="http://dl.dropbox.com/u/1938726/Screenshots/fd1w.png" />

EDIT: I just reread this thread. Looks like it's all being taken care of already ;)

**Comment by thomasmoon** [comment]
I was also perplexed by this, but luckily found this issue and it was easy to update.

Is there no way to force submodules to update when checking out a fresh clone?  Perhaps this step could be mentioned here in the installation docs:
http://frapi.github.com/installing/index.html#frapi.installing.getting.frapi.cloning

**Comment by dshafik** [comment]
I have created a PR (frapi/frapi.github.com#5) to fix the documentation. Additionally, #128 will help users with this problem.
