### ISSUE TITLE
not able to setup api.frapi

### ISSUE THREAD

**Issue by juzerarsi** [frapi/frapi#138]
hi
   I am working on php 5.2.6 on Apache.. i was able to set up admin.frapi/  however when i tried setting up api.frapi/ i encountered this error

"Parse error: syntax error, unexpected T_FUNCTION in E:\xampp\htdocs\frapi\src\frapi\custom\Output\html\Introduction.html.tpl on line 15"

I have already added api.frapi to my host file.. since i am trying to work locally
updated the httpd.conf file  to add the virtual host

<VirtualHost *:80>
    ServerName api.frapi
    ServerAdmin admin@api.frapi
    DocumentRoot FRAPI_PATH/src/frapi/public 

```
# This should be omitted in the production environment
SetEnv APPLICATION_ENV development

<Directory FRAPI_PATH/src/frapi/public>
    AllowOverride All
    Order deny,allow
    Allow from All
</Directory>
```

</VirtualHost>

and updated the  FRAPI_PATH correctly..

can anyone throw a light on what might be the problem

Thanks

**Comment by epixa** [comment]
Two months ago, code was added to that file that would only work in PHP 5.3.0 or above.  I'm not sure if it was intentional to make frapi >= 5.3 or not.
