### ISSUE TITLE
zend_codegenerator not found when syncing

### ISSUE THREAD

**Issue by erikverreycken** [frapi/frapi#140]
Hi I'm given a frapi setup that is not my work
but I'm getting a couple of errors when trying to sync the codebase 
because for some reason frapi can't find the zend/codeGenerator class 
however the class is present in the correct directory

Warning: include_once(Zend/CodeGenerator/Php/Class.php): failed to open stream: No such file or directory in /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader.php on line 146

Warning: include_once(): Failed opening 'Zend/CodeGenerator/Php/Class.php' for inclusion (include_path='/Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/') in /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader.php on line 146

Fatal error: Class 'Zend_CodeGenerator_Php_Class' not found in /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/models/Action.php on line 387

since I'm new to this frapi setup I'm not sure exactly where to look has anyone had this error before or does anyone know why all the other classes could be included exept this one

I have checked the filepermissions 
there are no other errors in this frapi setup

complete error stack:
Warning: include_once(Zend/CodeGenerator/Php/Class.php): failed to open stream: No such file or directory in /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader.php on line 146

Call Stack:
    0.3507     651432   1. {main}()                                         /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/public/index.php:0
    0.9750    8370792   2. Zend_Application->run()                          /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/public/index.php:24
    0.9750    8370792   3. Zend_Application_Bootstrap_Bootstrap->run()      /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Application.php:366
    0.9753    8371112   4. Zend_Controller_Front->dispatch()                /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Application/Bootstrap/Bootstrap.php:97
    0.9837    9020904   5. Zend_Controller_Dispatcher_Standard->dispatch()  /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Front.php:954
    1.0200   10392312   6. Zend_Controller_Action->dispatch()               /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Dispatcher/Standard.php:289
    1.0210   10399728   7. ActionController->syncAction()                   /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Action.php:513
    1.0321   10648112   8. Default_Model_Action->sync()                     /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/controllers/ActionController.php:271
    1.0322   10651480   9. Default_Model_Action->updateAction()             /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/models/Action.php:347
    1.0401   12073032  10. Zend_Loader_Autoloader::autoload()               /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/models/Action.php:0
    1.0403   12074120  11. call_user_func()                                 /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader/Autoloader.php:130
    1.0403   12074152  12. Zend_Loader_Autoloader->_autoload()              /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader/Autoloader.php:130
    1.0404   12074200  13. call_user_func()                                 /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader/Autoloader.php:474
    1.0404   12074232  14. Zend_Loader::loadClass()                         /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader/Autoloader.php:474
    1.0405   12074704  15. Zend_Loader::loadFile()                          /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader.php:94

Warning: include_once(): Failed opening 'Zend/CodeGenerator/Php/Class.php' for inclusion (include_path='/Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/') in /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader.php on line 146

Call Stack:
    0.3507     651432   1. {main}()                                         /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/public/index.php:0
    0.9750    8370792   2. Zend_Application->run()                          /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/public/index.php:24
    0.9750    8370792   3. Zend_Application_Bootstrap_Bootstrap->run()      /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Application.php:366
    0.9753    8371112   4. Zend_Controller_Front->dispatch()                /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Application/Bootstrap/Bootstrap.php:97
    0.9837    9020904   5. Zend_Controller_Dispatcher_Standard->dispatch()  /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Front.php:954
    1.0200   10392312   6. Zend_Controller_Action->dispatch()               /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Dispatcher/Standard.php:289
    1.0210   10399728   7. ActionController->syncAction()                   /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Action.php:513
    1.0321   10648112   8. Default_Model_Action->sync()                     /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/controllers/ActionController.php:271
    1.0322   10651480   9. Default_Model_Action->updateAction()             /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/models/Action.php:347
    1.0401   12073032  10. Zend_Loader_Autoloader::autoload()               /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/models/Action.php:0
    1.0403   12074120  11. call_user_func()                                 /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader/Autoloader.php:130
    1.0403   12074152  12. Zend_Loader_Autoloader->_autoload()              /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader/Autoloader.php:130
    1.0404   12074200  13. call_user_func()                                 /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader/Autoloader.php:474
    1.0404   12074232  14. Zend_Loader::loadClass()                         /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader/Autoloader.php:474
    1.0405   12074704  15. Zend_Loader::loadFile()                          /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Loader.php:94

Fatal error: Class 'Zend_CodeGenerator_Php_Class' not found in /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/models/Action.php on line 387

Call Stack:
    0.3507     651432   1. {main}()                                         /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/public/index.php:0
    0.9750    8370792   2. Zend_Application->run()                          /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/public/index.php:24
    0.9750    8370792   3. Zend_Application_Bootstrap_Bootstrap->run()      /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Application.php:366
    0.9753    8371112   4. Zend_Controller_Front->dispatch()                /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Application/Bootstrap/Bootstrap.php:97
    0.9837    9020904   5. Zend_Controller_Dispatcher_Standard->dispatch()  /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Front.php:954
    1.0200   10392312   6. Zend_Controller_Action->dispatch()               /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Dispatcher/Standard.php:289
    1.0210   10399728   7. ActionController->syncAction()                   /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/library/Zend/Controller/Action.php:513
    1.0321   10648112   8. Default_Model_Action->sync()                     /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/controllers/ActionController.php:271
    1.0322   10651480   9. Default_Model_Action->updateAction()             /Volumes/Data/ServiceData/Web/Public/develop/frapi/backend/src/frapi/admin/application/modules/default/models/Action.php:347

**Comment by davidcoallier** [comment]
Can you show us your `frapi/src/frapi/application/configs/application.ini` ? I'm mostly looking for somewhere where the index path would have been changed.

**Comment by erikverreycken** [comment]
this is my application.ini

[production]
phpSettings.date.timezone = "Europe/London"
phpSettings.display_startup_errors = 0
phpSettings.display_errors = 0
debug = 0

;;;;;; Setup ZF ;;;;;;

bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"

resources.modules.default = default

resources.frontController.moduleDirectory = APPLICATION_PATH "/modules"
;resources.frontController.params.noErrorHandler = true
resources.frontController.plugins[] = "Zend_Controller_Plugin_ErrorHandler"
resources.layout.layoutPath = APPLICATION_PATH "/views/layouts"

resources.view.helperPath.Lupin_View_Helper = ROOT_PATH "/library/Lupin/View/Helper"
resources.view.helperPath.App_View_Helper   = APPLICATION_PATH "/views/helpers"
resources.view.scriptPath.App_View          = APPLICATION_PATH "/views/scripts"

;;;;; Standard extension to ZF ;;;;;;
autoloaderNamespaces.lupin = "Lupin_"
;;;;; Application specific library ;;;;;;
autoloaderNamespaces.frapi = "Frapi_"

;;;;;; App related configuration ;;;;;;;

acl.defaultRole  = user;
acl.roles.user   = null;
acl.roles.admin  = user;

user.salt = "453&^%&$#$%#@=GDFFD"

; User session expires after 45 minutes of inactivity
session.expire = 2700

smtp.hostname        = "smtp.gmail.com";
smtp.config.auth     = "login";
smtp.config.username = "";
smtp.config.password = "";
smtp.config.ssl      = "ssl";
smtp.config.port     = 465;

resources.db.adapter         = pdo_sqlite
resources.db.params.username = frapi
resources.db.params.password = frapi
resources.db.params.dbname   = ../frapi.sqlite
resources.db.params.hostname = localhost
;resources.db.params.port    = 555
resources.db.isDefaultTableAdapter = false

[staging : production]

[testing : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1
phpSettings.error_reporting = -1
autoloaderNamespaces.mock = "MockFrapi_"
autoloaderNamespaces.action = "Action_"

[development : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1
phpSettings.error_reporting = -1
