### ISSUE TITLE
Object not found error when a rest service is called

### ISSUE THREAD

**Issue by juzerarsi** [frapi/frapi#141]
hi,
   I have installed Frapi. using (Apache 2.2.21, PHP: 5.3.8) xampp 1.7.7

I created a basic public Action without any parameters and tried testing it. However, i am getting object not found error. 

Here is my action
/num - public
i am returning a random string in the executeGet() method
$this->data = array('rand' => 'dom');

When i try testing the action -the URL created is
http://api.frapi/num.json

 i get this error - 
Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.
If you think this is a server error, please contact the webmaster.
Error 404

Am i missing something ?
Thanks

**Comment by dshafik** [comment]
@juzerarsi What do you get when visiting http://api.frapi/ ?

Can you show us your Apache `VirtualHost` configuration? Also, have you correctly setup your hosts file?

What is the output of `ping api.frapi` from the command line?

**Comment by dshafik** [comment]
@juzerarsi I'm going to close this ticket as we haven't heard any feedback. If you are still encountering this issue, please re-open this ticket.
