### ISSUE TITLE
JSONP output should have content type of application/javascript

### ISSUE THREAD

**Issue by clayhinson** [frapi/frapi#146]
In the JSON output formatter [JSON.php](https://github.com/frapi/frapi/blob/master/src/frapi/library/Frapi/Output/JSON.php#L59), JSONP output is sent using the content type 'application/json'. This should be sent as 'application/javascript' since the response is interpreted as pure JS instead of JSON.

**Comment by scoates** [comment]
+1

**Comment by dshafik** [comment]
This should be fixed by #145 and #147
- #145: will now respond with the requested mimetype (e.g. Accept: application/javascript will respond with `application/javascript`)
- #147: if you request `.js` extension, it now defaults to `application/javascript` (used to be `text/javascript`)
