### ISSUE TITLE
Admin Tester "Load Email/Key Combo" doesn't actually load the combo.

### ISSUE THREAD

**Issue by jeremykendall** [frapi/frapi#15]
The email and key combo appear in the select element correctly.  Selecting them does not populate the email and key combo fields, however.

**Comment by davidcoallier** [comment]
The new authentication system now uses HTTP Auth Digest instead of Basic auth. The Admin Tester has to be adjusted accordingly.

**Comment by davidcoallier** [comment]
Fixed by Trevor in http://github.com/frapi/frapi/commit/86e24519b3ce040dcc229024c4552aa0576a75b6
