### ISSUE TITLE
Main controller method getParams() parses input each time it's called

### ISSUE THREAD

**Issue by clayhinson** [frapi/frapi#167]
The current implementation of Main::getParams is such that it parses the input stream each time it's called. This method is called at least 3 times during initialization. The work of processing input should be done once and getParams should return the output of that. 
This isn't much of an issue in normal circumstances but can cause lag in processing during large file uploads, as it reads the entire php://input stream.

**Comment by dshafik** [comment]
@clayhinson I'll look over this tomorrow when I get a chance — at first glance it looks fine, but I want to pull it down and run the tests and such.
