### ISSUE TITLE
Adding custom methods

### ISSUE THREAD

**Issue by Max13** [frapi/frapi#169]
Hello !

I know it's bad...
But I'm trying to add custom methods (like LOGIN) to my frapi fork, because my JS app sends me "LOGIN isn't allowed by Access-control-allow-methods".

I don't find this header in frapi, and adding
`header('Access-control-allow-methods: GET, PUT, POST, DELETE, HEAD, LOGIN', true);`

doesn't send it to the browser.
Thanks for you help.

**Comment by dshafik** [comment]
@Max13 REST only supports standard HTTP methods, we do not support the addition of custom methods like this — you're getting into the realms of RPC and standard MVC actions (next thing you know, you'll have a PROFILE method, and an EDIT method ;).

You should be logging in using OAuth or HTTP Digest authentication against a resource using one of the standard methods.

I'm going to close this as it isn't something we will implement, sorry.

**Comment by Max13** [comment]
Sorry but, I don't want you to implement them, I just want to override the accepted one.
I know that it's against RFC's and else.

Currently, I'm already using "custom" methods on other projects, we don't have problems with that because we're requesting the resources with custom methods not from a browser.

Today I tried an ajax call (with custom method) on an iPhone, that's why I just want to send a "support" for custom methods.

BTW, even if there is a PROFILE and an EDIT methods, the reponse header is `Access-control-allow-methods: POST,GET,PUT,DELETE,HEAD`, so they're also considered invalid :/
