### ISSUE TITLE
Deleting error, action, probably anything that touches xml file breaks xml

### ISSUE THREAD

**Issue by trevormorse** [frapi/frapi#17]
With the sample errors.xml code like this:

<pre>
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;frapi-config&gt;
 &lt;errors&gt;
  &lt;error&gt;
   &lt;name&gt;ERROR_EXAMPLE&lt;/name&gt;
   &lt;message&gt;This is an example error.&lt;/message&gt;
   &lt;http_code&gt;405&lt;/http_code&gt;
   &lt;description&gt;This error is used as an example for both the API and the automatically generated documentation which can be found at admin.frapi/docs/generate/format/md&lt;/description&gt;
   &lt;hash&gt;e06f885297d44a9faf5703252c638b3dcdec6986&lt;/hash&gt;
  &lt;/error&gt;
  &lt;error&gt;
   &lt;name&gt;TEST&lt;/name&gt;
   &lt;message&gt;The error&lt;/message&gt;
   &lt;http_code&gt;404&lt;/http_code&gt;
   &lt;description&gt;Used in documentation&lt;/description&gt;
   &lt;hash>137595984a31492d0637fe873922537b13094e53&lt;/hash&gt;
  &lt;/error&gt;
 &lt;/errors&gt;
&lt;/frapi-config&gt;
</pre>

If I remove the ERROR_EXAMPLE entry via the interface the xml then looks like this:

<pre>
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;frapi-config&gt;
 &lt;errors&gt;
  &lt;error&gt;
   &lt;error&gt;
    &lt;name&gt;TEST&lt;/name&gt;
    &lt;message&gt;The error&lt;/message&gt;
    &lt;http_code&gt;404&lt;/http_code&gt;
    &lt;description&gt;Used in documentation&lt;/description&gt;
    &lt;hash&gt;137595984a31492d0637fe873922537b13094e53&lt;/hash&gt;
   &lt;/error&gt;
  &lt;/error&gt;
&lt;/errors&gt;
&lt;/frapi-config&gt;
</pre>

Note the double opening and closing error tags. Which causes the following php error:

Notice: Undefined index: name in FRAPI_PATH/src/frapi/admin/application/modules/default/views/scripts/errors/index.phtml on line 15

**Comment by davidcoallier** [comment]
Oddly enough, this happens only once and I'm not sure why it does that. I'm going to investigate.

**Comment by davidcoallier** [comment]
Git pull and you'll have the fix.
