### ISSUE TITLE
problem installing Frapi

### ISSUE THREAD

**Issue by mirlo06** [frapi/frapi#182]
hi , 
during the installation of frapi on windows I get an error, "Internal Server Error 500" what should I do? help me thanks.

**Comment by DanielRuf** [comment]
me too, doesnt work with the install instructions from http://frapi.github.com/installing/index.html (windows and uniform server)

**Comment by mirlo06** [comment]
i configured the APC, a page is displayed called "API Documentation" but I have not understood the concerns.

**Comment by mirlo06** [comment]
ok i fixed my problem :)

**Comment by mirlo06** [comment]
hi ,
Daniel  are you working a project  android invoking  webservice Frapi ?

**Comment by DanielRuf** [comment]
No, you should consider asking the frapi team and create an issue. I think I can not help you.

**Comment by mirlo06** [comment]
thnx
