### ISSUE TITLE
invoking a web service Frapi from Android

### ISSUE THREAD

**Issue by mirlo06** [frapi/frapi#187]
hi ,
What is the request to invoke a web service Frapi in android 
 i try with http://api.frapi/login but no answer.

**Comment by dshafik** [comment]
@mirlo06 FRAPI uses standard HTTP as it's communication protocol; any standards compliant HTTP client should be able to access a FRAPI-based web service. I'm sure Android's SDK provides one.

However, we cannot support 3rd party clients, as this is outside the scope of our project. Personally, I test with browsers, httpie, curl, Zend_Rest_Client and general PHP (e.g. `file_get_contents()`) code, and all have worked successfully.

If you have an issue with FRAPI itself (for example, if it is unable to handle a correct client request), please don't hesitate to open up another ticket.

**Comment by mirlo06** [comment]
hi @dshafik ,
i work on ubuntu , I'm sure that there is no problem with FRAPI ( configuration )cause when i execute 
curl -X POST http://api.frapi/index  -H 'Content-Type: application/json'   its work  ! 

this is some of the file index.php  

```
public function executePost()
{
```

$this->data=array('name' => 'marwen' , 
                      'email' => 'newram06@gmail.com' );
        return $this->toArray();
}

ps : its working with Tester Frapi .

and this is the code for a client Android :
public class Main extends Activity implements OnClickListener{

```
//Create a HTTPClient as the form container
HttpClient httpclient;

//Use HTTP POST method
HttpPost httppost;

//Create an array list for the input data to be sent
ArrayList<NameValuePair> nameValuePairs;

//Create a HTTP Response and HTTP Entity
HttpResponse response;
HttpEntity entity;



@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);

        httpclient = new DefaultHttpClient();

    //Create new HTTP POST with URL to php file as parameter
    httppost = new HttpPost("http://api.frapi/index.php");

    try{
        response = httpclient.execute(httppost);
        if(response.getStatusLine().getStatusCode()== 200){

            //assign response entity to http entity
            entity = response.getEntity();

            //Create new input stream with received data assigned
            InputStream instream = entity.getContent();

            //Create new JSON Object. assign converted data as parameter.
            JSONObject jsonResponse = new JSONObject(convertStreamToString(instream));
            String s=jsonResponse.toString();
            Toast.makeText(getBaseContext(),s, Toast.LENGTH_SHORT).show();}
        else {
            Toast.makeText(getBaseContext(), " erreur "+response.getStatusLine().getStatusCode(), Toast.LENGTH_SHORT).show();

        }


    }catch(Exception e)
    {
        Toast.makeText(getBaseContext(), " erreur response ", Toast.LENGTH_SHORT).show();
    }
```

}

```
private static String convertStreamToString(InputStream is) {
    /*
     * To convert the InputStream to String we use the BufferedReader.readLine()
     * method. We iterate until the BufferedReader return null which means
     * there's no more data to read. Each line will appended to a StringBuilder
     * and returned as String.
     */
    BufferedReader reader = new BufferedReader(new InputStreamReader(is));
    StringBuilder sb = new StringBuilder();

    String line = null;
    try {
        while ((line = reader.readLine()) != null) {
            sb.append(line + "\n");
        }
    } catch (IOException e) {
        e.printStackTrace();
    } finally {
        try {
            is.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    return sb.toString();
}//END convertStreamToString()
```

}

SO IT DIDN'T WORK , like you say , sure tha Android's sdk provides one like SOAP but i searching and i didn't find

**Comment by mirlo06** [comment]
no answers !

**Comment by mirlo06** [comment]
@trevormorse  help please

**Comment by dshafik** [comment]
@mirlo06 as I've said (and you've said), this is **not**  a FRAPI issue; sorry. This issue is closed, and will remain so.
