### ISSUE TITLE
Installing shared server or dedicated

### ISSUE THREAD

**Issue by yaba** [frapi/frapi#194]
[EDIT]
Thanks to Max13 and some sleep, It's now working!!!!

Hi,
I've spent the last 2 hours trying to install this into my servers.
On shared hosting.... 0
On private server.... 0
I dislike Recessframework, and thought that Frapi would be a nice option... screw this... i'm going to sleep and re-install recess...
BTW... Followed every single step on the FEW docs here, also, i'm not some kind of newbie around the Linux world.
...

**Comment by Max13** [comment]
Hi,
Where are you stuck ?

**Comment by yaba** [comment]
First of all, sorry the language and lack of details, I was angry and it was late.
On shared hosting, I've quited, so nevermind this.
On private server, I can now see the main login page, and then "/login not found" 
BTW, I've deleted everything and stick with Recess again :(
But if you could help me, I'll try again. This time with more details.

**Comment by Max13** [comment]
No problems.
I'm CEO of a french webhosting service, I can assure you it works perfectly on shared webhosting. Basically, it's the same on private server, except that you can change the conf to match your own needs, but it can make frapi fail.

So, first of all, we have free offers, if you took your private server for frapi. You can come on our server.
If you still want to keep your private server, you have to correctely install Apache/PHP, then test it with a single test page (like phpinfo();).

Then, if it works, try to install frapi as it's written in the README and come back to tell me where you're stuck in the process, which page you see, what are your apache configs concerning the URL, and what you see on your screen.

**Comment by yaba** [comment]
Check it:
http://CENSURED/frapi/src/frapi/admin/public/
The GUI is messed up. And then: Sorry! A system error prevented your action from being executed

**Comment by Max13** [comment]
You missed your Apache config. Read this: http://frapi.github.com/installing/index.html#frapi.installing.configuring.apache

If you don't find, I will give you a hint ;)

**Comment by yaba** [comment]
Nop... I missed the path. I've changed the .htaccess and now it's working (more or less)
There's still this:
git submodule update --init
Shared hosting, I can't access git :( :(

**Comment by Max13** [comment]
Yeah, .htaccess are made to modify your apache config ;)
Actually, you can't use git, but nothing prevent you to clone the git locally and upload it with FTP, SFTP, SCP or whatever.

**Comment by yaba** [comment]
Ok, so... Now I need some help. I have this .htaccess:

SetEnv APPLICATION_ENV development

RewriteEngine On
#RewriteRule ^/$ /home/CENSORED/frapi/src/admin/public/
#RewriteCond %{REQUEST_FILENAME} -s [OR]
#RewriteCond %{REQUEST_FILENAME} -l [OR]
#RewriteCond %{REQUEST_FILENAME} -d
#RewriteRule ^._$ - [NC,L]
#RewriteRule ^._$ index.php [NC,L]

RewriteCond %{HTTP_HOST} ^testeapagar.CENSORED.pt$ [NC,OR]
RewriteCond %{HTTP_HOST} ^www.testeapagar.CENSORED.pt$
RewriteCond %{REQUEST_URI} !frapi/src/frapi/public/
RewriteRule (.*) /frapi/src/frapi/public/$1 [L]

The coment part is the original from frapi, the rest is what made it work, I can access the admin or public by changing the .htaccess, but how can I test the json output ?

**Comment by Max13** [comment]
Try this instead:
1) Take the exact .htaccess frapi gives you and install it to your DOCUMENT_ROOT.
2) Take your apache config, change the DOCUMENT_ROOT value to ".../src/frapi/public".
3) Then, you'll have a correct environment, if it fails, we can go step by step from there.

**Comment by yaba** [comment]
I would do that If I could change the document root (shared hosting)
I'll try and let you know.

**Comment by Max13** [comment]
Aren't you allowed to make subdomains point on a chosen subdirectory ?
Or they force your subdomain to point on the "/subdomain" dir ?

**Comment by yaba** [comment]
Done that, 500 internal error :| Let me check the error.log

**Comment by yaba** [comment]
Ok, working, now... 
Should I make 2 subdomains? one for the public and other for admin/public ?

**Comment by Max13** [comment]
Exactely.

**Comment by yaba** [comment]
I really don't like that option but that's ok :)
Later I'll clone the git and try again.
Thanks Adnan! really!

**Comment by Max13** [comment]
You have no choice unfortunately.
Personnaly, I have "api.domain.com" and "admin.api.domain.com".

And you're welcome, my name is Adnan.

**Comment by yaba** [comment]
Ok, so now I'm trying /collection/res1 and getting some errors about templates.
Anyway, this is not anymore an installation issue, I'll check the manual to get it started.
Thanks again.

**Comment by Max13** [comment]
Don't hesitate to come on our server if you need/want, I (and my team) will be able to provide you better help by support ticket or Mailing-list, which is very usefull ;)

And don't hesitate to ask anything again.

**Comment by yaba** [comment]
Max13, one more help please :)
Shouldn't frapi come with json already working?
I only have 2 template folders, html and xml

**Comment by davidcoallier** [comment]
Hey there @yaba 

It does JSON, XML, PHP, JSONP, etc by default. 

The 2 template folders are in case you need custom html and custom xml code.

try this:

```
[term~]$ curl http://api.frapi/collection -H 'Accept: application/json'
.. json output ..
[term~]$ curl http://api.frapi/collection -H 'Accept: application/xml'
```

Depending on the content type received, the server will negotiate and return the good type.

**Comment by yaba** [comment]
That's odd, I checked again at github, and the files json.php do exist. but i've cloned and did the modules thing and I don't have them.
should i clone frapi-common ?

**Comment by Max13** [comment]
Just try you apis with .json ;)

**Comment by yaba** [comment]
empty array, but yes,  comes in json

**Comment by yaba** [comment]
Maybe I misunderstood the documentation but, by simply configure the database and create a new action with the table's name, shouldn't it return the values?

**Comment by yaba** [comment]
:| I did misunderstood the docs... So this is no good for my kind of problem (users adding their own databases), they can't write code :) :) Damn Recess, you win again :|

**Comment by davidcoallier** [comment]
What? How does recess win? What does it win? :)

**Comment by yaba** [comment]
Sorry, I needed something simple so that one can:
1 - Create a DB/Table with defined parameters/fields
2 - Generate code based on that DB/Table so that the data will be available via json or xml
3 - Have some kind of security, like API keys, basic auth, etc...

Ok, so Recess sucks realtime in security, but having to generate code in Frapi is not an option.
Anyway, I did like it after all the trouble to install on shared hosting :)
Keep up the good work.
Thanks for all.

**Comment by trevormorse** [comment]
Closing this. I think everything has been "sorted".
