### ISSUE TITLE
api documentation page not working after I deleted example actions that came with installation

### ISSUE THREAD

**Issue by manoveg** [frapi/frapi#216]
Hi,

I am using frapi and it is working fine as such. I deleted example custom actions that initially came (Collection,Introduction,Resource,Sibling,Siblings) and then after that api documentation page is not loading. Api's are working fine though.

I am getting following error message when I am typing api.frapi in url
FRAPI Encountered some errors

Name: ERROR_INVALID_ACTION_REQUEST, with message: Invalid requested action,

**Comment by trevormorse** [comment]
Hi,

The Introduction action is what generates the documentation page, so you'll have to add it back if you want the documentation.
