### ISSUE TITLE
Problem with installing in Ubuntu Server

### ISSUE THREAD

**Issue by felas8** [frapi/frapi#222]
Hi
i have one problem with installation, i follow the guide, http://frapi.github.io/installing/index.html#frapi.installing.directory.and.file.permissions
but when i try http://ipserver/admin.frapi i have this error:

The requested URL /admin.frapi was not found on this server.

If i try to navigate in http://ipserver/frapi/src/frapi/admin/public/  i see the login page with username and password but when i try to access i have the error
The requested URL /frapi/src/frapi/admin/public/login was not found on this server.

**Comment by felas8** [comment]
i have enabled  Apache rewrite module, i also add admin.frapi to your /etc/hosts file, but still nothing.. help..

my .htaccess in /var/www/frapi/src/frapi/admin/public is:

SetEnv APPLICATION_ENV development

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^._$ - [NC,L]
RewriteRule ^._$ index.php [NC,L]

And in my  apache2.conf i put this:

VirtualHost *:80>
    ServerName admin.frapi
    DirectoryIndex index.php
    ServerAdmin admin@api.frapi

```
# This should be omitted in the production environment
SetEnv APPLICATION_ENV development

DocumentRoot /var/www/frapi/src/frapi/admin/public
<Directory /var/www/frapi/src/frapi/admin/public>
    AllowOverride All
    Order deny,allow
    Allow from All
</Directory>
```

</VirtualHost

**Comment by chriskuhar** [comment]
With apace Ubuntu the pattern is to create a /etc/apache2/sites-available/frapi.conf then symbolic link it to /etc/apache2/sites-enabled/frapi.conf

Of course frapi.conf can be any file name.

Move that code to the conf file, restart apache

**Comment by felas8** [comment]
yes i create a file admin.frapi.conf..i follow this guide: http://oiga.dejensever.com/2013/06/16/instalando-frapi-un-framework-para-crear-una-rest-api/

but still nothing.. maybe the file .htaccess isn't valid?

**Comment by davidcoallier** [comment]
The the htaccess file works for many others, so whilst possible, I doubt it's the issue in this case.

Did you create a separate host entry in your hosts file?

**Comment by felas8** [comment]
in my hosts file i have : 

127.0.0.1 localhost
127.0.1.1 homenet.telecom.com
127.0.2.1 admin.frapi

for now when i create the file api.frapi.conf i add to hosts file 127.0.3.1  api.frapi

i try to install in local with VirtualBox

**Comment by davidcoallier** [comment]
Try

```
127.0.0.1 localhost
127.0.0.1 homenet.telecom.com
127.0.0.1 admin.frapi
```

**Comment by felas8** [comment]
if i try in this mode i have this error:

apache2: Could not reliably determine the server's fully qualified domain name,using 127.0.0.1 for ServerName

if i try another ip, 192.168.1.156 or 127.0.1.0 i have same error:

Not Found

The requested URL /admin.frapi was not found on this server.

Apache/2.2.22 (Ubuntu) Server at 192.168.1.156 Port 80

**Comment by felas8** [comment]
i follow this step:

1) sudo a2enmod rewrite
2) sudo apt-get install php-apc
3) sudo apt-get install php-gettext
4) sudo apt-get install git
5) move into /var/www
6) git clone git://github.com/frapi/frapi.git
7) chown -R www-data /vr/www/frapi
8)chmod 775 /var/www/frapi/src/frapi/custom/Action
9)chmod 775 /var/www/frapi/src/frapi/custom/Config/
10)chmod 664 /var/www/frapi/src/frapi/custom/Config/*.xml
11) go in /etc/apache2/sites-available and create a admin.frapi.conf with this configuration:

```
ServerName admin.frapi
DirectoryIndex index.php
ServerAdmin admin@api.frapi

# This should be omitted in the production environment
SetEnv APPLICATION_ENV development

DocumentRoot /var/www/frapi/src/frapi/admin/public
<Directory /var/www/frapi/src/frapi/admin/public>
    AllowOverride All
    Order deny,allow
    Allow from All
</Directory>
```

12) add 127.0.0.1 admin.frapi in /etc/hosts file
13)sudo ln -s /etc/apache2/sites-available/admin.frapi.conf /etc/apache2/sites-enabled/
14) reboot VirtualMachine UbuntuServer 12.04 in VirtualBox
15) open browser and try 192.168.1.156/admin.frapi---->ERROR

**Comment by davidcoallier** [comment]
The URL is not `192.168.1.156/admin.frapi` but `http://admin.frapi`

**Comment by felas8** [comment]
but my Server is Virtual, with VirtualBox, and have a 192.168.1.156 ip address
for example if i try 192.168.1.156/frapi/src it works, i see the directory but 192.168.1.156/admin.frapi i have error

**Comment by davidcoallier** [comment]
You'll probably have to add those hosts entries to point to that server then.

**Comment by felas8** [comment]
you mean in the /etc/hosts add:

192.168.1.156 admin.frapi

?

**Comment by davidcoallier** [comment]
Yes but make sure you are forwarding the ports outside the Virtual Machine.

**Comment by felas8** [comment]
you mean the port 80 ?.. but is the VirtualBox setting wrong ?

if i try in my LinuxMint --> sudo ufw show listening

tcp:
  139 \* (smbd)
  389 \* (slapd)
  445 \* (smbd)
  631 \* (cupsd)
tcp6:
  139 \* (smbd)
  389 \* (slapd)
  445 \* (smbd)
  631 \* (cupsd)
  80 \* (apache2)
udp:
  137 192.168.1.255 (nmbd)
  137 192.168.1.100 (nmbd)
  137 \* (nmbd)
  138 192.168.1.255 (nmbd)
  138 192.168.1.100 (nmbd)
  138 \* (nmbd)
  44475 \* (avahi-daemon)
  5353 \* (avahi-daemon)
  68 \* (dhclient)
  9504 \* (dhclient)
udp6:
  47339 \* (avahi-daemon)
  47554 \* (dhclient)
  5353 \* (avahi-daemon)

**Comment by felas8** [comment]
i post also the network error:

Request URL:http://192.168.1.156/admin.frapi
Request Method:GET
Status Code:404 Not Found

Request Headersview source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Encoding:gzip,deflate,sdch
Accept-Language:it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Cookie:PHPSESSID=h7cah4eeacq3dgma7v3l3p3er2
Host:192.168.1.156
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.62 Safari/537.36

Response Headersview source
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:241
Content-Type:text/html; charset=iso-8859-1
Date:Mon, 02 Sep 2013 09:52:36 GMT
Keep-Alive:timeout=5, max=100
Server:Apache/2.2.22 (Ubuntu)
Vary:Accept-Encoding

And if i go in http://192.168.1.156/frapi/src/frapi/admin/public/  i have this result

public/
/frapi/src/frapi/admin  METHOD GET  

STATUS 403 Forbidden

**Comment by felas8** [comment]
i solved!!finally!.. now works!!
