### ISSUE TITLE
Cant configure virtualhost

### ISSUE THREAD

**Issue by ferngical** [frapi/frapi#227]
Hello Everyone,
               Can you please have alternate solution to virtualhost. I am working on a shared server so dont have access to httpd.conf file neither I have can create subdomain. Can you provide me solution with htaccess files which will work like

http://myip/frapi

and this will take to client side

http://myip/frapi/admin

will take me to admin side..

Please bit urgent since i have really played enough with .htaccess

**Comment by shredz** [comment]
Please let me know for the answer to above query

**Comment by davidcoallier** [comment]
For security and simplicity reasons, those should be on 2 separate domains (subdomains). You should set it up as
1. http://api.frapi.com or http;//frapi.com for the main api
2. http://admin.frapi.com for the admin interface.
