### ISSUE TITLE
Duplicate bootstrap causes fatal error when generating code coverage

### ISSUE THREAD

**Issue by jeremykendall** [frapi/frapi#25]
Received when running unit tests:

Generating code coverage report, this may take a moment.PHP Fatal error:  Cannot redeclare class Default_Bootstrap in /home/jeremykendall/public_html/frapi/src/frapi/admin/application/modules/default/controllers/Bootstrap.php on line 20

**Comment by jeremykendall** [comment]
Resolved in https://github.com/frapi/frapi/pull/26.

**Comment by davidcoallier** [comment]
Resolved.
