### ISSUE TITLE
Let's localize more

### ISSUE THREAD

**Issue by memfill** [frapi/frapi#31]
ActionController.php has about half the output still in English only (embedded), and I am not talking error output only, there are still bits that addMessage like $this->addMessage('Development environment has been sychronized'); (line 234)

**Comment by davidcoallier** [comment]
Good catch, Want to go over them and change them? Or i can do it tomorrow :)

**Comment by memfill** [comment]
Sure thing, I will take care of that. I will go over the error output as well. Give me a day or 2

**Comment by memfill** [comment]
Well since this will take time, let's close this for now.

**Comment by davidcoallier** [comment]
Ok keep me posted, I"ve pulled your latest changes, and most stuff should be there now.
