### ISSUE TITLE
Localizing Lupin

### ISSUE THREAD

**Issue by memfill** [frapi/frapi#37]
I have a small problem:

Submitting NULL values triggers Lupin response with the default placeholder that we need to localize.
/src/frapi/library/Lupin/Form.php:  'isEmpty'  => 'This field requires a value but you submitted nothing.', is the example

Can we set programatically default form values from within the forms or controllers of the admin application?

**Comment by helgi** [comment]
That message is actually coming from Zend_Form and not Lupin_Form. Lupin_Form only extends Zend_Form, tho there are cases of hard coded English values.

There are a fair few good resources on how to localize Zend_Form out there - And I believe with the right things passed to the config it will automagically translate the built in messages.

I will investigate soon but if anyone beats me to it, that's fine.

**Comment by memfill** [comment]
I see. What I don't get though is the fact that Zen form elements are invoked and localized directly from controllers/forms/views. Should we just extend the isEmpty into the application and localize it locally?

Check out the label setting on form elements from within the /forms/

**Comment by memfill** [comment]
Ok for David:

David, I propose removing attachment of validators at Form_Lupin (line 115) since this gets applied on the addElement that runs the prepareElement and effectively erases validators added by individual forms. 
This is bad especially since I can not localize these values.
I propose the following:

Remove attachment of validators in Lupin_Form
We will replace it by the following, in the Form code of each form as necessary:

$company->addValidator('NotEmpty', true, array('messages' => array('isEmpty' => $tr->_('GENERAL_MISSING_TEXT_VALUE'))));

**Comment by memfill** [comment]
Solved and patched  in https://github.com/frapi/frapi/commit/61c42a64dd049863fb4460fefa4ec01268af72fe
