### ISSUE TITLE
Frapi_Output_XML_Exception

### ISSUE THREAD

**Issue by danielhunt** [frapi/frapi#53]
After accessing http://api.frapi/foo.xml?param1=bar, I get:

```
<response>
  <errors>
    <error code="Frapi_Output_XML_Exception">
      <message>Invalid XML element name, cannot create element.</message>
      <name>Frapi_Output_XML_Exception</name>
      <at/>
    </error>
  </errors>
</response>
```

It'd be nice if this error gave some sort of indication as to what portion of the output is causing a problem for rendering :)
- Output in JSON format (http://api.frapi/foo?param1=bar) works perfectly fine so that could be used to debug

**Comment by davidcoallier** [comment]
Good point. This is usually due to passing an object instead of an array but a tad more information in the message would do good indeed.

**Comment by danielhunt** [comment]
Hrm, well there are no objects in my $this->data .... but I'll hold out for some updates to see if it will tell me what it doesn't like.

Cheers

**Comment by davidcoallier** [comment]
Can you show me a dump or a serialized object dump?
