### ISSUE TITLE
Problem with /custom/config/errors.xml file

### ISSUE THREAD

**Issue by hibrid** [frapi/frapi#63]
I can't tell exactly what the problem is but whenever I've used a pull of Frapi (as of this writing), there is an error after deleting an error but only on the first error I delete inside the admin interface.  It doesn't matter if I've added additional errors first or not.  

The end result is that in the admin, the errors page is blank.  You can add new errors and those will show up but the already existing errors do not show up. 
What is happening is that the delete is successful but the remaining errors are wrapped with an additional <error> tag.  So you end up with something like this (image its XML) :
errors 
error

error
   Error Data

/error

error
  Error Data

/error

/error

/errors

The solution I found was to recreate the errors.xml file and save it back in.  This solves the problem. I'm guessing there is a weird character in the file that is breaking things but the fix is simple enough.

FYI: I haven't tried to recreate the problem on a Unix platform.  I wrote the article on running Frapi in IIS 7 you recently tweeted about so naturally, I am running Frapi on IIS 7.5 with Wincache.

Please let me know if you have any questions.

**Comment by davidcoallier** [comment]
Yep I've noticed this as well, it happens with the actions as well. I'm working on a fix for that.

**Comment by clayhinson** [comment]
This problem should be fixed as of last week, please pull and let us know if you're still seeing this problem.
