### ISSUE TITLE
Location of the $data variable

### ISSUE THREAD

**Issue by SeanJA** [frapi/frapi#65]
Not an issue really, I am just curious why it is not in the Frapi_Action class or the Frapi_Action_Interface one? Does it not get added to each of the Action_\* classes that are generated?

http://frapi.github.com/developing/coding-actions.html has it as a private variable.

**Comment by davidcoallier** [comment]
Well the `$data` is what you are returning. You populate the data variable and return it from your executes. The `$data` variable is merely a container used to decouple the data you want to return and how to carry it around your controller methods. 

From your **_executeGet**_ you should as well return the following:

``` php
<?php
public function executeGet() 
{
    return array('test' => 'value');
}
```
