### ISSUE TITLE
Output type determination priority

### ISSUE THREAD

**Issue by elgrafico** [frapi/frapi#68]
Since commit 231a420a68b7a2f6cac247cfdea5626ca1b09c58 , requesting a ressource via URI does not override accept header.
imho, http://$HOST/$RESSOURCE.xml should return xml no matter what the accept header is.

**Comment by davidcoallier** [comment]
The headers content acceptation priority would override this but I'll look at this and discuss with Clay and a few other people and get back to you on this.

**Comment by elgrafico** [comment]
fixed in 231a420a68b7a2f6cac247cfdea5626ca1b09c58, thanks clayhinson!
