### ISSUE TITLE
Missing armchair submodule from frapi.git

### ISSUE THREAD

**Issue by philip** [frapi/frapi#7]
The Armchair submodule isn't linking properly. In other words, this:

git clone git://github.com/frapi/frapi.git

Ends up with an empty frapi/custom/Model/Armchair directory. 

A workaround is to git clone git://github.com/till/armchair.git separately.

**Comment by Theaxiom** [comment]
I have not done much with submodules yet, but I believe you have to update the submodules before you pull. ("git submodule init", then "git submodule update") and that should resolve your issue

**Comment by davidcoallier** [comment]
Thanks for reporting this, I'll look at it. I thought it was solved but apparently not :)

**Comment by davidcoallier** [comment]
Thanks @Theaxiom :) I'll add that to the wiki page :)

**Comment by davidcoallier** [comment]
Updated the wiki with a comment about making sure to git submodule init and update

**Comment by philip** [comment]
I updated the wiki too, but am unsure how best to handle this situation with 'downloads' as it's missing from the tarball.

http://wiki.github.com/frapi/frapi/downloading-frapi

**Comment by jeremykendall** [comment]
For linux users, setup.sh now includes initializing and updating the Armchair submodule.

See http://github.com/frapi/frapi/commit/aa987365d2176e5214bdc68b7fb5a7bb2caacfd9
