### ISSUE TITLE
Notice error in documentation generator for no parameter actions

### ISSUE THREAD

**Issue by baohx2000** [frapi/frapi#73]
When viewing /docs under the admin api or trying to generate pdf documentation
Notice: Undefined index: parameters in /home/baoh/www/frapi/src/frapi/admin/application/modules/default/views/scripts/docs/generate.phtml on line 22

This is because the "sibling" example action has no parameters set up.  

This issue also causes PDF generation to fail since the server will shoot out the error before the PDF header.

**Comment by davidcoallier** [comment]
You are completely right. I'll get this fixed asap. Good catch!
