### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by bennocrombeen** [frapi/frapi#74]
At the moment there are 10 failures in the unit test:

FAILURES!
Tests: 140, Assertions: 151, Failures: 10, Incomplete: 11, Skipped: 7.

**Comment by davidcoallier** [comment]
Could you send us which tests are failing for you please?

Thank you very much!

**Comment by bennocrombeen** [comment]
Frapi_Input_XmlParser::arrayFromXml Fraoi_Error message is not consitent with the test

**Comment by davidcoallier** [comment]
Ok thanks, I'll get this sorted.

**Comment by bennocrombeen** [comment]
I forgot to mention that the first (fatal) error I got was this:
Unsupported operand types in /home/benno/www/frapi/src/frapi/library/Frapi/Output/XML.php on line 89

**Comment by bennocrombeen** [comment]
The problem seems to be in In Frapi_Output_XML::_normalizeToArray.
The $input is NULL, so the $output var is set to NULL too. The body of the method checks for an object or an array. I corrected by changing the return value to an empty array if $output is NULL.

**Comment by bennocrombeen** [comment]
Other failures are like the following:

There were 2 failures:

1) Frapi_Output_XMLTest::testExpectedXML with data set #5 (array(array(1, 2, array('c', 'd', 'e'))), '<response>
                    <a>
                        <numeric-key>1</numeric-key>
                        <numeric-key>2</numeric-key>
                        <numeric-key>
                            <c/>
                            <d/>
                            <e/>
                        </numeric-key>
                    </a>
                </response>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 <?xml version="1.0"?>
 <response>
-  <a>1</a>
-  <a>2</a>
  <a>
-    <numeric-key>1</numeric-key>
-    <numeric-key>2</numeric-key>
-    <numeric-key>
-      <c/>
-      <d/>
-      <e/>
-    </numeric-key>
-    <c/>
-    <d/>
-    <e/>
  </a>
  </response>

/home/benno/www/frapi/src/frapi/tests/unit-tests/library/Frapi/Output/XMLTest.php:68

2) Frapi_Output_XMLTest::testExpectedXML with data set #6 (array(array('d', 'x', array('-_invalid_nodeName', '123_invalidNodeName'))), '<response>
                    <a_b>
                        <d/>
                        <x/>
                        <_ssl>
                            <numeric-key>-_invalid_nodeName</numeric-key>
                            <numeric-key>123_invalidNodeName</numeric-key>
                        </_ssl>
                    </a_b>
                </response>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 <?xml version="1.0"?>
 <response>
   <a_b>
     <d/>
     <x/>
-    <_ssl>
-      <numeric-key>-_invalid_nodeName</numeric-key>
-      <numeric-key>123_invalidNodeName</numeric-key>
-    </_ssl>
-    <_ssl>-_invalid_nodeName</_ssl>
-    <_ssl>123_invalidNodeName</_ssl>
  </a_b>
  </response>

**Comment by bennocrombeen** [comment]
Hi David,

In the code I noticed the following:
In the method arrayFromXml in the class Frapi_Input_XmlParser, there is a
return of a new Frapi_Exception.

In the class Frapi_Input_RequestBodyParser there is a check (instanceof) if
the returned value is a Frapi_Exception and then it is thrown. Shouldn't it
be better to throw the exception in the first place?

Kind regards,

Benno Crombeen

2011/6/21 davidcoallier <
reply@reply.github.com>

**Comment by davidcoallier** [comment]
Yep definitely. If you want to issue a pull request I'll merge it and push it.
