### ISSUE TITLE
json_encode needs utf8 data

### ISSUE THREAD

**Issue by ziggamon** [frapi/frapi#77]
frapi / src / frapi / library / Frapi / Output / JSON.php

Line: 79

```
$returnedData = json_encode($this->response);
```

For some reason this doesn't always happen. 

Got it to work by using a snipped I ripped of php.net to JSON-encode arrays (probably should handle objects as well?)

```
function utf8_encode_all($dat) // -- It returns $dat encoded to UTF8 
{ 
  if (is_string($dat)) return utf8_encode($dat); 
  if (!is_array($dat)) return $dat; 
  $ret = array(); 
  foreach($dat as $i=>$d) $ret[$i] = utf8_encode_all($d); 
  return $ret; 
} 
```

Then it worked. Probably is another way of doing this. Unclear why i got this error though since my database is in utf8 already. Perhaps server configs are at play here too...

**Comment by davidcoallier** [comment]
Hmm this is odd, can you tell me which version of PHP you are currently using please?

If possible an excerpt of your data that's failing would be great as well!

**Comment by ziggamon** [comment]
Not really sure how I could send the data to you. Pretty sure it's the database handler that's converting stuff to iso somewhere. 

I'm using PHP 5.3.5

**Comment by davidcoallier** [comment]
How are you connecting to your database? Are you using Frapi_Database or something custom within your own models?

**Comment by ziggamon** [comment]
Plain PDO.

2011/6/30 davidcoallier <
reply@reply.github.com>

**Comment by davidcoallier** [comment]
Right under your connecting declaration add this:

``` php
    $pdo->setAttribute(PDO::MYSQL_ATTR_INIT_COMMAND, "SET NAMES utf8");
```

Let me know if this helps :)

**Comment by ziggamon** [comment]
Didn't help

2011/6/30 davidcoallier <
reply@reply.github.com>

**Comment by JiDai** [comment]
I have the same problem.
I use Frapi_Database.
I tried to :
1) change the line 110 in frapi/library/Frapi/Database.php by :

```
return $dsn.';charset=UTF8';
```

2) as written above, add the line to specify the charset on Frapi_Database object

``` php
 $db->setAttribute(PDO::MYSQL_ATTR_INIT_COMMAND, "SET NAMES utf8");
```

My table are type MyISAM and use utf8_general_ci collation

PHP Version 5.3.3-7+squeeze3

**Comment by JiDai** [comment]
I finally got it.

On line 65 in Database.php, I add the command PDO::MYSQL_ATTR_INIT_COMMAND in PDO contructor.
It doesn't work with `setAttribute` method

``` php
self::$instance[$name] = new PDO(
                    $dsn,
                    $configs['db_username'],
                    $configs['db_password'],
                    array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8')
                );
```

And `charset=UTF8` at the end of dsn is useless

Hope this help.
