### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by ziggamon** [frapi/frapi#78]
Updating: it seems this is related to the setting of JSON being default output not being respected.

Use case:

I don't want HTML output, and I want it to default to JSON. 

Going into a custom controller, like /potatoes gives me this error:

_MISSING_HTML_TEMPLATE, with message: If you want HTML, you need to create Potatoes.html.tpl in the frapi/src/frapi/custom/Output/html directory_

/potatoes.json works just fine though. 

Any ideas?

**Comment by davidcoallier** [comment]
That's because we handle the **Accept** header with priorities and your browser is sending _text/html_ with priority 9

**Comment by ziggamon** [comment]
But I want to disable HTML completely...

2011/6/30 davidcoallier <
reply@reply.github.com>

**Comment by davidcoallier** [comment]
This priority handling is a relatively new feature and we are aware/fixing of the "Default" output issue :)

**Comment by dshafik** [comment]
This is a duplicate of #108 which better summarizes the issue.
