### ISSUE TITLE
Is Partner data available to actions?

### ISSUE THREAD

**Issue by jcane86** [frapi/frapi#80]
Hey everybody, I'm not actually sure if this is a feature request or a documentation request, but anyhow, I'm developing an API where different users need to be presented with their respective info.
What I actually need to do is get the name (email?) for the partner that is accessing the API so I know what data I should answer with.
I know I could have everybody pass in theri username with their requests, but since they are already authenticating, I don't think it makes sense.
Is there any way to know who is calling the API?? from the action code.

Thanks!!

By the way, awesome framework you got here, keep up the good work!

**Comment by davidcoallier** [comment]
The only partner data available from **actions** is the username which you can retrieve from the $_SERVER superglobal.

Look for $_SERVER['X_AUTH_USER'] and it should be in there.

**Comment by jcane86** [comment]
Cool, thanks a lot!!

**Comment by mutasim** [comment]
I actually found the user name at $_SERVER['X_FRAPI_AUTH_USER']

**Comment by davidcoallier** [comment]
Ah yeah that's it, sorry for the confusion :-)
