### ISSUE TITLE
default parameters in url

### ISSUE THREAD

**Issue by danelowe** [frapi/frapi#81]
It would be great if we could easily create actions with parameters in the URL, while allowing the parameters to be optional, similar to the way the standard Zend router allows. 

For example urls such as

/orders/
/orders/1234/
/orders/1234/lines/

Each param could have a default value e.g  'null', 'all' or 'view' defined in the router config for when it is missing from the URL

**Comment by davidcoallier** [comment]
You'd have to define your custom route as such:

```
/orders
/orders/:id
/orders/:id/:type
```

And those would be three different "actions". Considering the first one would be a collection of "orders" where you can execute _GET_ to retrieve a list of orders and _POST_ to add new orders. The second one would be the order-resource so you could execute the likes of _GET_ to retrieve the resource information, _PUT_ to update its information, _DELETE_ to remove this resource and _HEAD_ to retrieve its meta information. The third call would be something I call resource-helpers which is just a drilldown of some property on the resource.

Let me know if this helps.

**Comment by danelowe** [comment]
Perfect, thanks. The way you describe it explains the multiple actions as
being more of a beneficial feature than optional parameters in the url would
be. Makes a lot of sense.

**Comment by davidcoallier** [comment]
The main rationale being this logic is: _All those calls serve different purposes, therefore, they are different actions_

:)
