### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by mutasim** [frapi/frapi#82]
The platform I am using doesn't yet support Digest Auth, what would be my best route to implementing Basic Auth?

Reversing these changes?

https://github.com/frapi/frapi/commit/5486683fedbec04e1d8d158e8d15cee1fa5fc9b6

**Comment by davidcoallier** [comment]
FRAPI handles everything with regards to headers and sending the challenge. What platform are you using so I can look into a better and proper solution for you?

**Comment by mutasim** [comment]
Basically I'm using XHR/JS to access the API, the platform I was referring to is the one I am building client apps on (Appcelerator Titanium), the've only implemented Basic Auth and I can't access the WWW-Authenticate header to retrieve the nonce or realm etc.

**Comment by davidcoallier** [comment]
Ahh right I understand better now. 

I wouldn't recommend reverting the core but rather develop a custom Auth module (As included in the source). Another thing you could do is use api-keys per user that you generate on your side, then using a custom auth module you either read the param from the URI (Less desirable) or from X-Authentication headers. 

If you really want to use the built-in Authentication it'll either be HTTP Digest or revert (Which I don't recommend).

If you need a hand building a custom auth module jump on irc.freenode.org on #frapi and we'll give you a hand :)
