### ISSUE TITLE
Class 'XMLWriter' not found

### ISSUE THREAD

**Issue by jorgecolonconsulting** [frapi/frapi#84]
For whoever maintains the documentation:
_could you add XMLWriter as a dependency in your installation page?_

I spent hours trying to figure this out. I was getting a "Class 'XMLWriter' not found" fatal error. I thought it was part of the Zend library or something. It ended up being that FRAPI has a dependency on the XMLWriter extension. Normally this is compiled into the PHP core, but on CentOS servers, like myself, it's sometimes NOT compiled into the core. I'm not too sure if it affects other distributions since XMLWriter is "usually" compiled into PHP from the get go.

If you're seeing this error make sure you are working with the correct PHP CLI. On my server there were two, one for PHP 5.2 and another for PHP 5.3. Drop in a phpinfo(); in a discrete file on your server and navigate to it. SSH into your server and type in `php -i`. The output should match, including the same PHP version. Check if If it's different issue a `locate bin/php` to see if there are multiple versions of PHP installed on your server. If that's so, use the path of the newly founded PHP and issue the same -i flag. For instance, if your "other" version of PHP was located at /usr/bin/php issue a `/usr/bin/php -i`. At that point you can install xmlwriter by using phpize and compiling it manually from the PHP sources of your specific PHP version. If you running into issues compiling after you issue `make` you might need to install the developer sources of certain packages. For instance, for me I was getting a pcre*.h error. I just installed the PCRE developer sources through yum with `yum install pcre-devel` then ran `make` again and XMLWriter compiled just fine.

**Comment by epixa** [comment]
I've added a pull request for this change to the frapi.github.com repo: https://github.com/frapi/frapi.github.com/pull/2

If you find other improvements that you think should be made, do not hesitate to fork that repo and issue a pull request.  That documentation is all in basic HTML.

**Comment by jorgecolonconsulting** [comment]
Oh nice. Now I know how to fork it. Thanks. :)
