### ISSUE TITLE
Stuff breaks when FRAPI is not at DocumentRoot

### ISSUE THREAD

**Issue by 3van** [frapi/frapi#86]
I have a VirtualHost set up with Alias directives pointing to the public/ and admin/public/ directories.

It looks like a lot of paths are defined in the templates with relative paths starting with a slash, so none of the JS/CSS/images load, and all the links are broken.

**Comment by davidcoallier** [comment]
Yes that's why we have a requirement to set 2 virtual hosts. You might be interested in looking at: https://github.com/frapi/frapi/issues/90
