### ISSUE TITLE
permission settings documentation

### ISSUE THREAD

**Issue by philip** [frapi/frapi#9]
The documentation still mentions 744, whereas setup.sh sets things to 777. The documentation should cover this, and also should mention a few words about chown options instead. Not too detailed, but something.

For a little history, the following commit altered setup.sh from 766 to 777:
- http://github.com/frapi/frapi/commit/3aa4e56f739faeb6992b7469affa16e3154f0e97

**Comment by davidcoallier** [comment]
I think they are all fixed now, could you let me know where you still see some if you still see them?

We are also working on something smarter than 777 :)

**Comment by davidcoallier** [comment]
Ok Jeremy made good leeway regarding the permissions for FRAPI, which can be found here:

http://groups.google.com/group/frapi-dev/browse_thread/thread/7f380662d4cdfac2

As soon as it's tested on multiple distros, we'll update the wiki and close this issue.

**Comment by davidcoallier** [comment]
Done and wiki updated as well!
