### ISSUE TITLE
Characters escaped when creating action

### ISSUE THREAD

**Issue by Max13** [frapi/frapi#96]
Hi again !

I've noticed that sometimes (with cache set to "dummy" or "apc") when creating action, then editing it online, the code is escaped when synced...
Actually, every $data['var1'] are escaped as $data[\'var1\'], even in comments.

Is it the normal behaviour, is it because I'm using single quote, or because I don't have any cache set...
Thank you for your help.

Example: http://pastebin.com/aYbNWqjK
Line 20, 39...

**Comment by trevormorse** [comment]
Can you please check your php.ini file for runtime configuration directive: magic_quotes_gpc, if it is on try turning it off and see if that fixes the issue.

**Comment by Max13** [comment]
Solved. Thank you.
